### ISSUE TITLE
gas optimization: stake & farm in 1 instead of 4 txs

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-farm#1]
The current setup requires 4 transactions from a user:
1. `approve` HOPR for Uni
2. add liquidity to Uni
3. approve Uni pool token for farm
4. `openFarm`

This could be simplified to a single tx:
1. send HOPR to farm contract, add liquidity to pool from there

Closing a farm, correspondingly, can be reduced from 2 (`closeFarm` followed by removing liquidity from Uni) to 1 tx.

**Comment by t0bij** [comment]
Good idea to make the entrance easier/cheaper for new liquidity providers. But it's ment to be as additional option, right? So the option to easily open a farm for people who are already liquidity providers on Uni remains untouched.

**Comment by QYuQianchen** [comment]
Agree with @t0bij. There's no need for existing LPs to take step 1 and 2. However, we can merge step 3 and 4 using the `permit` function of Uni Token. It asks for a signature of the token holder for `approve`, which reduces the number of transactions needed but would be less straight forward for a non-tech users interacting with the contract without our UI. 

We can prepare those functions to suit different needs tho.
