### ISSUE TITLE
Event IncentiveClaimed defined with "until" but triggered with "currentPeriod"

### ISSUE THREAD

**Issue by t0bij** [hoprnet/hopr-farm#9]
Event IncentiveClaimed is defined with an argument "until" but triggered with currentPeriod at this position.
https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L53
https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L281

"until" would be currentPeriod - 1:
https://github.com/hoprnet/hopr-farm/blob/41fb543aad7da97c9178ce49030bc463e1039097/contracts/HoprFarm.sol#L277

**Comment by QYuQianchen** [comment]
Agree.
